### ISSUE TITLE
Help: Unable to install package python-frank-energie==6.0.0

### ISSUE THREAD

**Issue by itavero** [bajansen/home-assistant-frank_energie#118]
Ik loop tegen een probleem aan als ik de integratie wil gebruiken in Home Assistant.
Eerder werkte en had ik dit opgelost, maar ik kan me niet meer herinneren hoe dit op te lossen en het ook niet meer vinden.

Als Home Assistant op start, verschijnt er een melding dat Frank Energie niet geladen wordt en staat de volgende entries in mijn logs:
```
Setup failed for custom integration 'frank_energie': Requirements for frank_energie not found: ['python-frank-energie==6.0.0'].

Unable to install package python-frank-energie==6.0.0: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local' Check the permissions.
```

Ik draai Home Assistant in een Docker container, via Docker Compose.
De entry voor HA ziet er als volgt uit:
```yml
  hass:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/ha:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    user: "1001:100"
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hass-remote.rule=Host(`doe.maar.een.domeintje.nl`)"
      - "traefik.http.services.hass-remote.loadbalancer.server.port=8123"
      - "traefik.http.routers.hass-remote.middlewares=cfonly@file"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      - mqtt
```
De configureerde user is ook de eigenaar van de config folder (`./data/ha`).

Hopelijk heeft iemand een idee hoe dit op te lossen.

**Update**: ik vermoed dat het komt doordat ik expliciet de user ze (`user: "1001:100"`). Ik ken echter geen andere manier om te zorgen dat de container de juiste rechten heeft in `./data.ha`. Als ik dit weghaal, lijkt het goed te gaan. Nu hopen dat het editen van de config files e.d. ook goed blijft gaan.
