### ISSUE TITLE
Automation trigger lowest price or highest price of the day

### ISSUE THREAD

**Issue by jayaarts** [bajansen/home-assistant-frank_energie#18]
Is it possible to create an automation to, for example, receive a notification if the price becomes the lowest (or highest) of the day?

**Comment by Tazzios** [comment]
You can do that with the build HA automation. You can compare current price with lowest and highest. As an action you can then send a notification. (sorry no example)

**Comment by jayaarts** [comment]
When I try to do this:
{{ states('sensor.current_electricity_price_all_in') | float == states('sensor.lowest_energy_price_today') | float }}

I get an error:
template value should be a string for dictionary value @ data['value_template']. Got None

Sorry, I'm new and helpless knowledge; trying to learn.

**Comment by bajansen** [comment]
The described template should work and it should also work without the casts to float. The lowest_energy_price_today value is retrieved from the same array as the current all-in price so the values should also be an exact match.

For me, the template `{{ states('sensor.current_electricity_price_all_in') == states('sensor.lowest_energy_price_today') }}` returns true or false as expected. Maybe the error occurs when the values have not yet been instantiated, such as when Home Assistant has just started.

**Comment by HiDiHo01** [comment]
I have created a binairy sensor for this in configuraton.yaml

  - binary_sensor:
      - name: Happy hour
        device_class: running
        state: >
          {{ states('sensor.current_electricity_price_all_in') | round(4,default=0) == states('sensor.lowest_energy_price_today') | round(4,default=0) }}

For my plugs (eg charging phone) I use this automation. It also plays a message on all my speakers

- id: '1651974863090'
  alias: Philips plug aan bij laagste tarief
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.happy_hour
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: d7ea19752753e08adbc9baa5128b75fa
    entity_id: switch.philips
    domain: switch
  - service: tts.zeg
    data:
      entity_id: media_player.huis
      message: De elektriciteitprijs is nu het laagst
      cache: true
  mode: single

**Comment by TFhdKi95ae8L** [comment]
For me the binary sensor mentioned above did not work in my configuration.yaml.
This one does:
```yaml
- platform: template
  sensors:
    happy_hour:
      unique_id: happyhour
      value_template: "{{ (states('sensor.current_electricity_price_all_in') | round(4,default=0) == states('sensor.lowest_energy_price_today') | round(4,default=1)) | default('off') }}"
```
