### ISSUE TITLE
Save sensor data to recorder database

### ISSUE THREAD

**Issue by Tazzios** [bajansen/home-assistant-frank_energie#19]
Is there an option to log the sensor data (current all-in-price ) to the longterm recorder database? 
The history in HA now only goes +-7 days back and I cannot find any data in the 'home-assistant_v2.db'

I wanted to calculate the production in euro's from my solar panel with the production and price information from the database.

**Comment by Tazzios** [comment]
I added the following to calculate it for each month

```
template:
  - sensor:
      - name: Zon_EUR_uur
        unit_of_measurement: EUR
        state:  >
          {% set opbrengst = states.sensor.Zon_KWH_uur.state | float %}
          {% set price = states.sensor.current_electricity_price_all_in.state | float %}
          {{ ((opbrengst * price) | round(2) )}}

utilitymeter:
  zon_opbrengst_maand_eur:
    name: Zon_EUR_maand
    source: sensor.Zon_EUR_uur
    cycle: monthly
```

For longer saving i installed the grafana and influx DB addon as explained in the forums and youtube.
